export const seedLeads = [
  {
    leadId: 'ND-001-2024',
    companyName: 'Dakota Digital Solutions LLC',
    naicsCode: '541512',
    naicsDescription: 'Computer Systems Design Services',
    ueiSAM: 'JK3LMN567890ABCD',
    cageCode: '7X9Y1',
    duns: '123456789',
    addressLine1: '1234 Broadway Ave',
    city: 'Fargo',
    stateCode: 'ND',
    zipCode: '58102',
    congressionalDistrict: 'ND-AL',
    businessType: ['2R', 'XX', 'A2'],
    sbaBusinessTypeDesc: ['Small Business', 'Woman-Owned Small Business'],
    registrationDate: new Date('2023-01-15'),
    expirationDate: new Date('2024-01-15'),
    registrationStatus: 'Active',
    primaryContactName: 'Sarah Johnson',
    primaryContactEmail: 'sjohnson@dakotadigital.com',
    primaryContactPhone: '701-555-0123',
    website: 'www.dakotadigital.com',
    probeStatus: 'pending',
    contracts: [
      {
        contractNumber: 'W911NF24C0123',
        title: 'IT Infrastructure Modernization',
        description:
          'SAMPLE DATA: This is seeded test data for demonstration purposes. Comprehensive network infrastructure upgrade including hardware refresh, security enhancements, and cloud migration strategy for military research facility. Includes 24/7 monitoring and maintenance.',
        value: 450000,
        awardDate: new Date('2024-01-15'),
        status: 'Active',
        isSample: true,
        isTest: false,
      },
      {
        contractNumber: 'GS35F0123X',
        title: 'Cloud Migration Services',
        description:
          'SAMPLE DATA: Mock contract for testing. Professional services for migrating legacy applications to AWS GovCloud. Includes application assessment, re-architecture, data migration, and staff training. Compliance with FedRAMP requirements.',
        value: 275000,
        awardDate: new Date('2023-08-20'),
        status: 'Completed',
        isSample: true,
        isTest: false,
      },
    ],
  },
  {
    leadId: 'ND-002-2024',
    companyName: 'Northern Plains Tech Services Inc',
    naicsCode: '541519',
    naicsDescription: 'Other Computer Related Services',
    ueiSAM: 'PQ8RST234567WXYZ',
    cageCode: '4A5B2',
    duns: '234567890',
    addressLine1: '5678 Main Street',
    city: 'Bismarck',
    stateCode: 'ND',
    zipCode: '58501',
    congressionalDistrict: 'ND-AL',
    businessType: ['2R', 'A5', 'QF'],
    sbaBusinessTypeDesc: [
      'Small Business',
      'Service-Disabled Veteran-Owned Small Business',
      'HUBZone',
    ],
    registrationDate: new Date('2023-03-20'),
    expirationDate: new Date('2024-03-20'),
    registrationStatus: 'Active',
    primaryContactName: 'Michael Anderson',
    primaryContactEmail: 'manderson@nptech.com',
    primaryContactPhone: '701-555-0456',
    website: 'www.nptech.com',
    probeStatus: 'pending',
    contracts: [
      {
        contractNumber: 'FA865024C5678',
        title: 'Network Security Assessment',
        description:
          'SAMPLE DATA: Test record for development. Comprehensive cybersecurity evaluation and penetration testing for Air Force base network infrastructure. Includes vulnerability assessment, risk analysis, and remediation recommendations with quarterly reporting.',
        value: 325000,
        awardDate: new Date('2024-03-10'),
        status: 'Active',
        isSample: true,
      },
    ],
  },
  {
    leadId: 'ND-003-2024',
    companyName: 'Prairie Star Engineering',
    naicsCode: '541330',
    naicsDescription: 'Engineering Services',
    ueiSAM: 'UV3WXY890123EFGH',
    cageCode: '8C9D3',
    duns: '345678901',
    addressLine1: '910 University Drive',
    city: 'Grand Forks',
    stateCode: 'ND',
    zipCode: '58201',
    congressionalDistrict: 'ND-AL',
    businessType: ['2R', 'XX', '8A'],
    sbaBusinessTypeDesc: [
      'Small Business',
      'Woman-Owned Small Business',
      '8(a) Program Participant',
    ],
    registrationDate: new Date('2023-02-10'),
    expirationDate: new Date('2024-02-10'),
    registrationStatus: 'Active',
    primaryContactName: 'Jennifer White',
    primaryContactEmail: 'jwhite@prairiestar.com',
    primaryContactPhone: '701-555-0789',
    website: 'www.prairiestar.com',
    probeStatus: 'pending',
    contracts: [
      {
        contractNumber: 'N6833524C0345',
        title: 'Facility Design and Engineering',
        description:
          'SAMPLE DATA: Demonstration record only. Complete architectural and engineering services for new Navy research facility. Includes site analysis, design development, construction documents, and project management. LEED Silver certification required.',
        value: 890000,
        awardDate: new Date('2024-02-05'),
        status: 'Active',
        isSample: true,
      },
      {
        contractNumber: 'W912DY23C0089',
        title: 'Environmental Assessment Services',
        description:
          'SAMPLE DATA: Mock data for UI testing. Environmental impact study and compliance assessment for Army Corps facility expansion project. Includes wetlands delineation, endangered species survey, and NEPA documentation.',
        value: 156000,
        awardDate: new Date('2023-11-12'),
        status: 'Completed',
        isSample: true,
      },
    ],
  },
  {
    leadId: 'ND-004-2024',
    companyName: 'Red River Cybersecurity Group',
    naicsCode: '541690',
    naicsDescription: 'Other Scientific and Technical Consulting Services',
    ueiSAM: 'IJ6KLM456789MNOP',
    cageCode: '1E2F4',
    duns: '456789012',
    addressLine1: '2468 Tech Parkway',
    city: 'Fargo',
    stateCode: 'ND',
    zipCode: '58104',
    congressionalDistrict: 'ND-AL',
    businessType: ['2R', 'A5'],
    sbaBusinessTypeDesc: [
      'Small Business',
      'Service-Disabled Veteran-Owned Small Business',
    ],
    registrationDate: new Date('2023-04-05'),
    expirationDate: new Date('2024-04-05'),
    registrationStatus: 'Active',
    primaryContactName: 'Robert Martinez',
    primaryContactEmail: 'rmartinez@redrivercyber.com',
    primaryContactPhone: '701-555-0234',
    website: 'www.redrivercyber.com',
    probeStatus: 'pending',
    contracts: [
      {
        contractNumber: 'HC104124C0234',
        title: 'Cybersecurity Risk Assessment',
        description:
          'SAMPLE DATA: Seeded test contract. Enterprise-wide cybersecurity risk assessment for DHS facility including network architecture review, threat modeling, vulnerability scanning, and security policy development. Includes incident response planning.',
        value: 425000,
        awardDate: new Date('2024-04-18'),
        status: 'Active',
        isSample: true,
      },
      {
        contractNumber: 'GS35F0567Y',
        title: 'Penetration Testing Services',
        description:
          'SAMPLE DATA: Demo purposes only. Advanced penetration testing and red team operations for critical government systems. Includes social engineering tests, physical security assessment, and wireless network testing with detailed remediation roadmap.',
        value: 185000,
        awardDate: new Date('2023-12-01'),
        status: 'Active',
        isSample: true,
      },
    ],
  },
  {
    leadId: 'ND-005-2024',
    companyName: 'Badlands IT Consulting',
    naicsCode: '541511',
    naicsDescription: 'Custom Computer Programming Services',
    ueiSAM: 'CD9EFG567890QRST',
    cageCode: '5G6H7',
    duns: '567890123',
    addressLine1: '1357 Innovation Blvd',
    city: 'Minot',
    stateCode: 'ND',
    zipCode: '58701',
    congressionalDistrict: 'ND-AL',
    businessType: ['2R', 'XX', 'QF'],
    sbaBusinessTypeDesc: [
      'Small Business',
      'Woman-Owned Small Business',
      'HUBZone',
    ],
    registrationDate: new Date('2023-05-12'),
    expirationDate: new Date('2024-05-12'),
    registrationStatus: 'Active',
    primaryContactName: 'Lisa Thompson',
    primaryContactEmail: 'lthompson@badlandsit.com',
    primaryContactPhone: '701-555-0567',
    website: 'www.badlandsit.com',
    probeStatus: 'pending',
    contracts: [
      {
        contractNumber: 'W15QKN24C0789',
        title: 'Custom Software Development',
        description:
          'SAMPLE DATA: Test database entry. Custom application development for logistics tracking system. Includes requirements analysis, agile development, user interface design, database implementation, and full system integration with existing DoD systems.',
        value: 560000,
        awardDate: new Date('2024-05-22'),
        status: 'Active',
        isSample: true,
      },
    ],
  },
  {
    leadId: 'ND-006-2024',
    companyName: 'Missouri River Technologies',
    naicsCode: '541513',
    naicsDescription: 'Computer Facilities Management Services',
    ueiSAM: 'AB4CDE123456UVWX',
    cageCode: '9I0J1',
    duns: '678901234',
    addressLine1: '8642 River Road',
    city: 'Bismarck',
    stateCode: 'ND',
    zipCode: '58503',
    congressionalDistrict: 'ND-AL',
    businessType: ['2R'],
    sbaBusinessTypeDesc: ['Small Business'],
    registrationDate: new Date('2023-06-18'),
    expirationDate: new Date('2024-06-18'),
    registrationStatus: 'Active',
    primaryContactName: 'David Chen',
    primaryContactEmail: 'dchen@missouririvertech.com',
    primaryContactPhone: '701-555-0890',
    website: 'www.missouririvertech.com',
    probeStatus: 'pending',
    contracts: [
      {
        contractNumber: 'FA302324C0456',
        title: 'Data Center Management',
        description:
          'SAMPLE DATA: Placeholder contract record. Comprehensive data center operations and maintenance including 24/7 monitoring, server management, backup/recovery services, and disaster recovery planning. SLA guarantees 99.9% uptime for mission-critical Air Force systems.',
        value: 625000,
        awardDate: new Date('2024-06-30'),
        status: 'Active',
        isSample: true,
      },
      {
        contractNumber: 'N0017824C0123',
        title: 'IT Help Desk Services',
        description:
          'SAMPLE DATA: Example data for testing interface. Tier 1-3 help desk support for Navy personnel including hardware/software troubleshooting, account management, training, and ticket system administration. 8am-8pm EST coverage with 2-hour response time.',
        value: 245000,
        awardDate: new Date('2024-01-08'),
        status: 'Active',
        isSample: true,
      },
    ],
  },
  {
    leadId: 'ND-007-2024',
    companyName: 'Northern Lights Data Analytics',
    naicsCode: '541611',
    naicsDescription:
      'Administrative Management and General Management Consulting Services',
    ueiSAM: 'YZ7ABC890123IJKL',
    cageCode: '2K3L4',
    duns: '789012345',
    addressLine1: '3579 Analytics Way',
    city: 'Fargo',
    stateCode: 'ND',
    zipCode: '58103',
    congressionalDistrict: 'ND-AL',
    businessType: ['2R', 'XX'],
    sbaBusinessTypeDesc: ['Small Business', 'Woman-Owned Small Business'],
    registrationDate: new Date('2023-07-22'),
    expirationDate: new Date('2024-07-22'),
    registrationStatus: 'Active',
    primaryContactName: 'Amanda Lee',
    primaryContactEmail: 'alee@northernlightsdata.com',
    primaryContactPhone: '701-555-0345',
    website: 'www.northernlightsdata.com',
    probeStatus: 'pending',
    contracts: [
      {
        contractNumber: 'GS00Q17NSD3003',
        title: 'Data Analytics and Business Intelligence',
        description:
          'SAMPLE DATA: Demonstration contract for UI development. Advanced analytics platform development with machine learning capabilities for predictive maintenance and resource optimization. Includes data visualization dashboards, ETL pipeline development, and analyst training program.',
        value: 375000,
        awardDate: new Date('2024-07-15'),
        status: 'Active',
        isSample: true,
      },
    ],
  },
  {
    leadId: 'ND-008-2024',
    companyName: 'Flickertail Systems Integration',
    naicsCode: '541519',
    naicsDescription: 'Other Computer Related Services',
    ueiSAM: 'EF1GHI345678MNOP',
    cageCode: '6M7N8',
    duns: '890123456',
    addressLine1: '4680 Systems Drive',
    city: 'Grand Forks',
    stateCode: 'ND',
    zipCode: '58202',
    congressionalDistrict: 'ND-AL',
    businessType: ['2R', 'A5', '8A'],
    sbaBusinessTypeDesc: [
      'Small Business',
      'Service-Disabled Veteran-Owned Small Business',
      '8(a) Program Participant',
    ],
    registrationDate: new Date('2023-08-30'),
    expirationDate: new Date('2024-08-30'),
    registrationStatus: 'Active',
    primaryContactName: 'James Wilson',
    primaryContactEmail: 'jwilson@flickertailsystems.com',
    primaryContactPhone: '701-555-0678',
    website: 'www.flickertailsystems.com',
    probeStatus: 'pending',
    contracts: [
      {
        contractNumber: 'W52P1J24C0678',
        title: 'Systems Integration Services',
        description:
          'SAMPLE DATA: Seeded mock contract. Enterprise systems integration project connecting legacy Army procurement systems with modern cloud-based platforms. Includes API development, middleware configuration, data synchronization, and comprehensive testing with cutover support.',
        value: 495000,
        awardDate: new Date('2024-08-25'),
        status: 'Active',
        isSample: true,
      },
      {
        contractNumber: 'FA487324C0901',
        title: 'Network Modernization',
        description:
          'SAMPLE DATA: Test record for demonstration. Complete network infrastructure overhaul for Air Force installation including fiber optic cabling, switching equipment upgrades, wireless access point deployment, and IPv6 migration. Supports 10Gbps backbone.',
        value: 310000,
        awardDate: new Date('2024-03-15'),
        status: 'Active',
        isSample: true,
      },
    ],
  },
];
