import { Lead } from '../src/app/schemas/lead.schema';

export const seedLeads: Lead[] = [
  {
    leadId: 'sample-1',
    companyName: 'Sample Company 1',
    naicsCode: '541512',
    naicsDescription: 'Computer Systems Design Services',
    city: 'Fargo',
    stateCode: 'ND',
    businessType: ['Small Business'],
    registrationStatus: 'Active',
    probeStatus: 'sample',
    contracts: [
      {
        contractNumber: 'SAMPLE-001',
        title: 'Sample IT Services Contract',
        description: 'Sample contract for IT services',
        value: 50000,
        awardDate: new Date('2025-11-15'),
        status: 'Active',
        isSample: true,
        isTest: false,
      },
    ],
  },
  {
    leadId: 'sample-2',
    companyName: 'Sample Company 2',
    naicsCode: '541519',
    naicsDescription: 'Other Computer Related Services',
    city: 'Bismarck',
    stateCode: 'ND',
    businessType: ['Small Business'],
    registrationStatus: 'Active',
    probeStatus: 'sample',
    contracts: [
      {
        contractNumber: 'SAMPLE-002',
        title: 'Sample Cybersecurity Contract',
        description: 'Sample contract for cybersecurity services',
        value: 75000,
        awardDate: new Date('2025-11-10'),
        status: 'Active',
        isSample: true,
        isTest: false,
      },
    ],
  },
  {
    leadId: 'sample-3',
    companyName: 'Sample Company 3',
    naicsCode: '541511',
    naicsDescription: 'Custom Computer Programming Services',
    city: 'Grand Forks',
    stateCode: 'ND',
    businessType: ['Small Business'],
    registrationStatus: 'Active',
    probeStatus: 'sample',
    contracts: [
      {
        contractNumber: 'SAMPLE-003',
        title: 'Sample Software Development Contract',
        description: 'Sample contract for software development',
        value: 60000,
        awardDate: new Date('2025-11-12'),
        status: 'Active',
        isSample: true,
        isTest: false,
      },
    ],
  },
  {
    leadId: 'sample-4',
    companyName: 'Sample Company 4',
    naicsCode: '541513',
    naicsDescription: 'Computer Facilities Management Services',
    city: 'Minot',
    stateCode: 'ND',
    businessType: ['Small Business'],
    registrationStatus: 'Active',
    probeStatus: 'sample',
    contracts: [
      {
        contractNumber: 'SAMPLE-004',
        title: 'Sample Data Center Management Contract',
        description: 'Sample contract for data center management',
        value: 80000,
        awardDate: new Date('2025-11-08'),
        status: 'Active',
        isSample: true,
        isTest: false,
      },
    ],
  },
  {
    leadId: 'sample-5',
    companyName: 'Sample Company 5',
    naicsCode: '541690',
    naicsDescription: 'Other Scientific and Technical Consulting Services',
    city: 'Jamestown',
    stateCode: 'ND',
    businessType: ['Small Business'],
    registrationStatus: 'Active',
    probeStatus: 'sample',
    contracts: [
      {
        contractNumber: 'SAMPLE-005',
        title: 'Sample Consulting Services Contract',
        description: 'Sample contract for consulting services',
        value: 45000,
        awardDate: new Date('2025-11-14'),
        status: 'Active',
        isSample: true,
        isTest: false,
      },
    ],
  },
  {
    leadId: 'sample-6',
    companyName: 'Sample Company 6',
    naicsCode: '541512',
    naicsDescription: 'Computer Systems Design Services',
    city: 'Dickinson',
    stateCode: 'ND',
    businessType: ['Small Business'],
    registrationStatus: 'Active',
    probeStatus: 'sample',
    contracts: [
      {
        contractNumber: 'SAMPLE-006',
        title: 'Sample Network Design Contract',
        description: 'Sample contract for network design',
        value: 55000,
        awardDate: new Date('2025-11-13'),
        status: 'Active',
        isSample: true,
        isTest: false,
      },
    ],
  },
  {
    leadId: 'sample-7',
    companyName: 'Sample Company 7',
    naicsCode: '541519',
    naicsDescription: 'Other Computer Related Services',
    city: 'Williston',
    stateCode: 'ND',
    businessType: ['Small Business'],
    registrationStatus: 'Active',
    probeStatus: 'sample',
    contracts: [
      {
        contractNumber: 'SAMPLE-007',
        title: 'Sample IT Support Contract',
        description: 'Sample contract for IT support',
        value: 40000,
        awardDate: new Date('2025-11-16'),
        status: 'Active',
        isSample: true,
        isTest: false,
      },
    ],
  },
  {
    leadId: 'sample-8',
    companyName: 'Sample Company 8',
    naicsCode: '541511',
    naicsDescription: 'Custom Computer Programming Services',
    city: 'Wahpeton',
    stateCode: 'ND',
    businessType: ['Small Business'],
    registrationStatus: 'Active',
    probeStatus: 'sample',
    contracts: [
      {
        contractNumber: 'SAMPLE-008',
        title: 'Sample Web Development Contract',
        description: 'Sample contract for web development',
        value: 65000,
        awardDate: new Date('2025-11-11'),
        status: 'Active',
        isSample: true,
        isTest: false,
      },
    ],
  },
  // Add some live records here
  // Temporarily removed to test live mode with no data
];